import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import './globals.css'

export const metadata = {
  title: 'IMDB',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
